#!/bin/bash

# adds additional digital inputs and relay outputs to the Raspberry Pi platforms

# the stock RPI Venus distribution includes two relays and two digital inputs
# adding the additional GPIO pins to /etc/venus/gpio_list
# makes additional digital inputs available
# all 5 defined digital inputs are activated by this script
#
# the Raspberry PI default is for the first 8 GPIO pins to have pull UPs
# and the remaining have pull DOWNs. This makes some digital input pins behave differently
# this script also installs a DT overlay that switches to pull UPs for all digital input pins
#
# Only the first relay can be assigned to a function: alarm, genertor start/stop or pump.
# Others are only provided manual on/off control from the menu.
# Six relays are supported. Only the first relay can be assigned to functions
# The remaining relays are manual on/off only.

# run manually initally, then called from reinstallMods
# to uninstall/deactivate, call this script with "uninstall" as first parameter

# Note, this script DOES require a system reboot.

gpioListFile="/etc/venus/gpio_list"
overlayFile="/u-boot/overlays/VenusGpioOverlay.dtb"
relayStateFile="/opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py"
configFile="/u-boot/config.txt"

# no log file for this package
packageLogFile=""

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

####### this is duplicate to code in CommonResources -- keep in case SetupHelepr has not been updated
# prevent installing if not a Raspberry Pi
if [ -f /etc/venus/machine ]; then
    machine=$(cat /etc/venus/machine)
fi
if [ -z $machine ]; then
    if [ -f "$installedFlag" ]; then
        logMessage "can't determine Venus device type - uninstalling"
        scriptAction='UNINSTALL'
    else
        logMessage "can't determine Venus device type - exiting"
		exit $INCOMPATIBLE_PLATFORM
    fi
elif [ $machine != "raspberrypi2" ] && [ $machine != "raspberrypi4" ]; then
    if [ -f "$installedFlag" ]; then
        logMessage "$packageName not compatible with $machine - uninstalling"
        scriptAction='UNINSTALL'
    else
        logMessage "$packageName not compatible with $machine - exiting"
		exit $INCOMPATIBLE_PLATFORM
    fi
fi

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    # display innitial message
    echo
    echo "This package makes the following modifications:"
    echo "  Activates all 5 predefined digital inputs"
    echo "  Changes all digital inputs to have pull-ups in stead of a mix of pull up/down"

    standardActionPrompt
fi

#### installing
if [ $scriptAction == 'INSTALL' ] ; then

    updateActiveFile "$gpioListFile"

    # modify relaystate.py for additional relays to prevent system calc crash
    updateActiveFile "$relayStateFile"
    
    # install DT overlay to for pull-ups on all digital inputs
    updateActiveFile $pkgFileSets/VenusGpioOverlay.dtb "$overlayFile"

    if [ $(grep -c "VenusGpioOverlay" "$configFile") == 0 ]; then
        logMessage "activating GPIO DT overlay"
        echo "#### change all digital inputs to pull ups" >> "$configFile"
        echo "dtoverlay=VenusGpioOverlay" >> "$configFile"
        echo "#### end change all digital inputs to pull ups" >> "$configFile"
        filesUpdated=true
    fi
fi

# uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    restoreActiveFile "$gpioListFile"
    restoreActiveFile "$overlayFile"
    restoreActiveFile "$relayStateFile"

    # remove mods from configFile - do not use restore in case other mods were made manually
    if [ -f "$configFile" ]; then
        if [ $(grep -c "#### change all digital inputs to pull ups" "$configFile") != 0 ]; then
            sed -i -e '/#### change all digital inputs to pull ups/,/#### end change all digital inputs to pull ups/d' "$configFile"
            filesUpdated=true
        fi
    fi
fi

if $filesUpdated ; then
    rebootNeeded=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript

